### PR TITLE
Add support for spawning Android broadcast receivers

### PR DESCRIPTION
**Pull request by oleavr**
By specifying the `receiver` and `action` aux options.

Also be as forgiving as the system if the class name is bare and does
not start with a period.

(Based on #212.)

### CODE REVIEW

**Comment by oleavr** [comment]
@0x3430D FWIW I couldn't get this working – no process is spawned so the `spawn()` eventually times out. I tried this and similar things on Android 8.0/8.1, both on an AVD and a real device:

```python
pid = device.spawn("com.facebook.katana",
    receiver="com.facebook.battery.monitor.ContinuousBatteryMonitorService$BroadcastReceiver",
    action="android.intent.action.BOOT_COMPLETED")
```

Anyway, I can't go down this rabbit-hole so I'll go ahead and merge this now.

**Comment by 0x3430D** [comment]
@oleavr Ok, I will take a look at this failure... ! BTW, it worked on my (simple) BroadcastReceiver test (AVD x86 / Android 8.1.0) so maybe I will understand the problem...

**Comment by 0x3430D** [comment]
Strange, I did the test on AVD x86 / Android 8.1.0 and I got no timeout... It looks like it succeed to spawn... BTW I got a crash (but also with device.spawn("com.facebook.katana")) maybe I didn't install facebook correctly (adb pulled from an official google non rooted AVD and install -g it on my non official rooted AVD): 

```
                   ACRA  E  Initializing ANR detector for process: com.facebook.katana
                   libc  F  Fatal signal 11 (SIGSEGV), code 2, fault addr 0xea740008 in tid 5537 (Jit thread pool), pid 5534 (facebook.katana)
                  DEBUG  F  #00 pc 003d4870  /system/lib/libart.so (art::ProfilingInfo::GetInlineCache(unsigned int)+64)
                         F  #01 pc 00123503  /system/lib/libart-compiler.so (_ZN3art8HInliner17GetInlineCacheJITEPNS_7HInvokeEPNS_16StackHandleScopeILj1EEEPNS_6HandleINS_6mirror11ObjectArrayINS7_5ClassEEEEE+211)
                         F  #02 pc 00122b9c  /system/lib/libart-compiler.so (art::HInliner::TryInlineFromInlineCache(art::DexFile const&, art::HInvoke*, art::ArtMethod*)+220)
                         F  #03 pc 001219d7  /system/lib/libart-compiler.so (art::HInliner::TryInline(art::HInvoke*)+2103)
                         F  #04 pc 0012105a  /system/lib/libart-compiler.so (art::HInliner::Run()+890)
                         F  #05 pc 0012de68  /system/lib/libart-compiler.so (art::HInliner::RunOptimizations(art::HGraph*, art::DexFile::CodeItem const*, art::DexCompilationUnit const&)+1112)
                         F  #06 pc 0012ae9a  /system/lib/libart-compiler.so (art::HInliner::TryBuildAndInlineHelper(art::HInvoke*, art::ArtMethod*, art::ReferenceTypeInfo, bool, art::HInstruction**)+4378)
                         F  #07 pc 00127f09  /system/lib/libart-compiler.so (art::HInliner::TryBuildAndInline(art::HInvoke*, art::ArtMethod*, art::ReferenceTypeInfo, art::HInstruction**)+1593)
                         F  #08 pc 0012270c  /system/lib/libart-compiler.so (art::HInliner::TryInlineAndReplace(art::HInvoke*, art::ArtMethod*, art::ReferenceTypeInfo, bool, bool)+124)
                         F  #09 pc 001215c0  /system/lib/libart-compiler.so (art::HInliner::TryInline(art::HInvoke*)+1056)
                         F  #10 pc 0012105a  /system/lib/libart-compiler.so (art::HInliner::Run()+890)
                         F  #11 pc 001809be  /system/lib/libart-compiler.so (art::OptimizingCompiler::MaybeRunInliner(art::HGraph*, art::CodeGenerator*, art::CompilerDriver*, art::DexCompilationUnit const&, art::
                            PassObserver*, art::VariableSizedHandleScope*) const+222)
                         F  #12 pc 001827fd  /system/lib/libart-compiler.so (art::OptimizingCompiler::RunOptimizations(art::HGraph*, art::CodeGenerator*, art::CompilerDriver*, art::DexCompilationUnit const&, art:
                            :PassObserver*, art::VariableSizedHandleScope*) const+7101)
                         F  #13 pc 001840c7  /system/lib/libart-compiler.so (art::OptimizingCompiler::TryCompile(art::ArenaAllocator*, art::CodeVectorAllocator*, art::DexFile::CodeItem const*, unsigned int, art::
                            InvokeType, unsigned short, unsigned int, art::Handle<art::mirror::ClassLoader>, art::DexFile const&, art::Handle<art::mirror::DexCache>, art::ArtMethod*, bool, art::VariableSizedHandl
                            eScope*) const+3383)
                         F  #14 pc 00186173  /system/lib/libart-compiler.so (art::OptimizingCompiler::JitCompile(art::Thread*, art::jit::JitCodeCache*, art::ArtMethod*, bool, art::jit::JitLogger*)+1107)
                         F  #15 pc 000e1d83  /system/lib/libart-compiler.so (art::jit::JitCompiler::CompileMethod(art::Thread*, art::ArtMethod*, bool)+163)
                         F  #16 pc 000e1cd7  /system/lib/libart-compiler.so (jit_compile_method+55)
                         F  #17 pc 003b8b4f  /system/lib/libart.so (art::jit::Jit::CompileMethod(art::ArtMethod*, art::Thread*, bool)+303)
                         F  #18 pc 003bb992  /system/lib/libart.so (art::jit::JitCompileTask::Run(art::Thread*)+626)
                         F  #19 pc 0059856b  /system/lib/libart.so (art::ThreadPoolWorker::Run()+91)
                         F  #20 pc 00597fbb  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+139)
                         F  #21 pc 00050445  /system/lib/libc.so (offset 0x21000)
                         F  #22 pc 000025db  /system/lib/libc.so (offset 0x1e000)
                         F  #23 pc 00000c16  /system/lib/libc.so (offset 0x1e000)
                         F  #24 pc 00050cc8  /data/local/tmp/re.frida.server/frida-agent-32.so (offset 0x165000)
                         F  #25 pc 0004552d  /data/local/tmp/re.frida.server/frida-agent-32.so (offset 0x165000)
                         F  #26 pc 0004b656  /data/local/tmp/re.frida.server/frida-agent-32.so (offset 0x165000)
                         F  #27 pc 0004b6bc  /data/local/tmp/re.frida.server/frida-agent-32.so (offset 0x165000)
                         F  #28 pc 00051f57  /data/local/tmp/re.frida.server/frida-agent-32.so (offset 0x165000)
                         F  #29 pc 00017baf  <anonymous:e6df5000>
                         F  #30 pc 0007aaba  /data/local/tmp/re.frida.server/frida-agent-32.so (offset 0x165000)
                         F  #31 pc 0056b320  /system/lib/libart.so (art::GetResolvedMethod(art::ArtMethod*, art::MethodInfo const&, art::InlineInfo const&, art::InlineInfoEncoding const&, unsigned char)+16)
```

**Comment by 0x3430D** [comment]
I tried to hook facebook BroadcastReceiver with the following script to determine what could happened : 

```
Java.perform(function () {

    BroadcastReceiver = Java.use('com.facebook.battery.monitor.ContinuousBatteryMonitorService$BroadcastReceiver');

    var onReceive  = BroadcastReceiver.onReceive.overload('android.content.Context', 'android.content.Intent');
    
    onReceive.implementation = function (c, i) {

        send('onReceive '+i);

        return this.onReceive(c, i); 
    }   
});
```

I never received the hook notification and I got this : 

```
                            Process com.facebook.katana created for broadcast com.facebook.katana/com.facebook.battery.monitor.ContinuousBatteryMonitorService$BroadcastReceiver
                            PID: 8568   UID:    GIDs: 

                 zygote  W  Unexpected CPU variant for X86 using defaults: x86
                         I  The ClassLoaderContext is a special shared library.
     CrashLoopRemedyLog  W  unable to delete remedy log, instaCrash: false
                         W  unable to delete remedy log, instaCrash: true
        facebook.katana  I  type=1400 audit(0.0:86): avc: denied { read } for name="vmstat" dev="proc" ino=4026532039 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=1
                   ACRA  E  Initializing ANR detector for process: com.facebook.katana
        facebook.katana  I  type=1400 audit(0.0:87): avc: denied { open } for path="/proc/vmstat" dev="proc" ino=4026532039 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissi
                            ve=1
         appstatelogger  V  Registered App State Logger stream with Breakpad
       dalvik-internals  W  ignoring failure to find _ZN3art12FaultManager35EnsureArtActionInFrontOfSignalChainEv: could not hook _ZN3art12FaultManager35EnsureArtActionInFrontOfSignalChainEv
                         V  hooked signal using trap ()
                         V  hooked sysv_signal using trap ()
                         V  hooked bsd_signal using trap ()
                         V  hooked sigaction using trap ()
                 zygote  I  Do partial code cache collection, code=9KB, data=26KB
                         I  After code cache collection, code=9KB, data=26KB
                         I  Increasing code cache capacity to 128KB
     CrashLoopRemedyLog  W  unable to delete remedy log, instaCrash: true
                 zygote  I  Thread[3,tid=8577,WaitingInMainSignalCatcherLoop,Thread*=0xe5ed9c00,peer=0x12e80dd0,"Signal Catcher"]: reacting to signal 3
                   libc  I  Requested dump for tid 8568 (facebook.katana)

                            Process com.facebook.katana (PID: 8568) ended
```

**Pull request merged**
