### PR TITLE
Fixed for Issue #241

### PR DESCRIPTION
**Pull request by gebing**

### CODE REVIEW

**Comment by oleavr** [comment]
Thanks! This is a great find. I'm a bit concerned about caching in this case, as other requests may end up hitting the wrong helper process. What do you think about making the `resume ()` implementation do a try/catch, and checking if `e is Error.INVALID_ARGUMENT` and if that is the case, retry the request on the other helper? (And if not, rethrow.)

**Comment by gebing** [comment]
i think your idea is ok, and i can modify this PR and do some test.

**Comment by gebing** [comment]
I have tested it and it works ok

**Comment by oleavr** [comment]
Looks great, thanks!

**Pull request merged**
